---
- name: '{{ ansible_name_module }} | cmd:podman_container | Podman create {{ module }}' 
  containers.podman.podman_container:
    detach: yes
    name: "nginx"
    pod: "cloudctl"
    state: "started"
    recreate: "true"
    image: "{{ upstream_registry }}/cloudctl/nginx"
    volume:
      - "{{ dir_platform }}/nginx:/var/www/html:z"
      - "{{ dir_platform }}/nginx/nginx.conf:/etc/nginx/nginx.conf:z"
      - "{{ dir_secrets }}/cloudctl/certs/ssl/server/cloudctl.crt:/nginx.crt"
      - "{{ dir_secrets }}/cloudctl/certs/ssl/server/cloudctl.pem:/nginx.key"
