---
- name: '{{ ansible_name_module }} | openssl_privatekey | SSL Private Key | CloudCtl Self Signed CA Key'
  openssl_privatekey:
    path: "{{ dir_secrets }}/registry/ssl/registry.key"
    size: 4096

- name: '{{ ansible_name_module }} | openssl_csr | Certificate Signing Request | Docker Registry'
  openssl_csr:
    mode: 0600
    path: "{{ dir_secrets }}/registry/ssl/registry.csr"
    privatekey_path: "{{ dir_secrets }}/registry/ssl/registry.key"
    common_name: "registry"
    subject_alt_name:
      - "DNS:registry.{{ domain_cluster }}"
      - "DNS:localhost"
      - "DNS:cloudctl"
      - "IP:10.88.0.1"
      - "IP:10.0.1.1"

- name: '{{ ansible_name_module }} | openssl_certificate | Self Signed 365d TTL Certificate | Docker Registry'
  openssl_certificate:
    mode: 0600
    path: "{{ dir_secrets }}/registry/ssl/registry.crt"
    privatekey_path: "{{ dir_secrets }}/registry/ssl/registry.key"
    csr_path: "{{ dir_secrets }}/registry/ssl/registry.csr"
    selfsigned_not_after: "+365d"
    selfsigned_digest: "sha256"
    provider: selfsigned

