---
- name: '{{ ansible_name_module }} | cmd:podman.rm | Podman purge haproxy'
  command:
    cmd: 'podman rm --force haproxy'
  no_log: true
  ignore_errors: true
  when: pod_force_rm == true

- name: '{{ ansible_name_module }} | file:absent | Podman purge haproxy'
  file:
    path: '{{ dir_tmp }}/{{ name_pod_cloudctl }}-haproxy.pid'
    state: absent
  when: pod_force_rm == true

- name: '{{ ansible_name_module }} | cmd:podman_container | Podman create {{ module }}' 
  containers.podman.podman_container:
    detach: yes
    name: "haproxy"
    pod: "cloudctl"
    state: "started"
    recreate: "true"
    image: docker.io/cloudctl/haproxy
    volume:
      - "{{ dir_platform }}/haproxy/haproxy.cfg:/haproxy.cfg:z"
      - "{{ dir_secrets }}/cloudctl/certs/ssl/server/cloudctl.crt:/haproxy.crt"
      - "{{ dir_secrets }}/cloudctl/certs/ssl/server/cloudctl.pem:/haproxy.key"
