---
- name: '{{ ansible_name_module }} | cmd:podman_container | Podman purge {{ module }}' 
  containers.podman.podman_container:
    name: "haproxy"
    state: "absent"
  when: pod_force_rm == true

- name: '{{ ansible_name_module }} | cmd:podman_container | Podman create {{ module }}' 
  containers.podman.podman_container:
    detach: yes
    name: "haproxy"
    pod: "cloudctl"
    state: "started"
    recreate: "true"
    image: quay.io/cloudctl/haproxy
    volume:
      - "{{ dir_platform }}/haproxy/haproxy.cfg:/haproxy.cfg:z"
      - "{{ dir_secrets }}/cloudctl/certs/ssl/server/cloudctl.crt:/haproxy.crt"
      - "{{ dir_secrets }}/cloudctl/certs/ssl/server/cloudctl.pem:/haproxy.key"
