---
- name: '{{ ansible_name_module }} | copy:content.date | Log CloudCtl bundle date'
  copy:
    content: "{{ lookup('pipe','date +%Y%m%d%H%M%S') }}"
    dest: '{{ dir_platform }}/nginx/bundle.date'
    mode: 0777

- name: '{{ ansible_name_module }} | file:absent | Purge pre-existing bundles'
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - "{{ dir_dmp }}/cloudctl.tar.xz"
    - "{{ dir_dmp }}//cloudctl.tar.xz.sha256"
    - '{{ dir_bundle }}/{{ tpdk_bundle_name }}'

- name: '{{ ansible_name_module }} | command:tar | build base cloudctl pod artifact bundle'
  command:
    cmd:
      tar -vc --use-compress-program='pigz -9'
           -f {{ dir_tmp }}/cloudctl.tar.xz
           -C {{ dir_local_home }}
         platform
  args:
    creates: "{{ dir_tmp }}/cloudctl.tar.xz"
    warn: false

- name: '{{ ansible_name_module }} | stat:sha256 | SHA cloudctl.tar.xz'
  command: 'sha256sum {{ dir_tmp }}/cloudctl.tar.xz'
  args:
    warn: false
    chdir: '{{ dir_tmp }}'
  register: bundle_sha

- name: '{{ ansible_name_module }} | copy:content.bcrypt_htpasswd | Generate Default Registry Basic Auth'
  copy:
    content: '{{ bundle_sha.stdout }}'
    dest: "{{ dir_tmp }}/{{ bundle_sha }}"
    mode: 0660

- name: '{{ ansible_name_module }} | command:tar.cvf | Build unified bundle with auxilary unpack+launch utilities'
  command:
    cmd:
      tar -vc --use-compress-program='pigz -9' -C {{ dir_tmp }}
          -f {{ tpdk_bundle_name }}
        init.sh
        {{ bundle_sha }}
        {{ bundle_name }}
  ars:
    chdir: '{{ dir_bundle }}'
    creates: '{{ dir_bundle }}/{{ tpdk_bundle_name }}'
    warn: false
