#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: 'RedHat | TRNO | bundle | prep.yml' 
  hosts: local
  vars_files:
    - 'vars/global.yml'
    - 'vars/git.yml'
    - 'vars/images.yml'
  vars:
    module: "dependencies"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
    dir_artifacts_manifest: "{{ dir_artifacts }}/data/manifests"
    dir_artifacts_openshift: "{{ dir_artifacts }}/data/openshift"
  roles:
    - dependencies
