#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: '{{ ansible_name }} | coredns.yml' 
  hosts: cloudctl
  become: true
  become_user: root
  vars_files:
    - 'vars/global.yml'
    - 'vars/run.yml'
    # 'vars/coredns.yml'
  vars:
    module: "coredns"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
    dns_forward: "8.8.8.8"
    db_time: "{{ coredns_date_YmdH }}"
    dns_zone: "{{ {{ domain_cluster }} | default(cloud.codectl.io) }}"
  roles:
    - role: coredns
      when: start_dns == true
