#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: '{{ ansible_name }} | konductor.yml' 
  hosts: cloudctl
  become: true
  become_user: root
  vars_files:
    - 'vars/global.yml'
    - 'vars/run.yml'
  vars:
    module: "konductor"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
  roles:
    - role: konductor
      when: start_konductor == true
