#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: '{{ ansible_name }} | cloudctl.yml' 
  hosts: cloudctl
  become_user: root
  become: true
  vars_files:
    - 'vars/global.yml'
  vars:
    module: "cloudctl"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
  roles:
    - pod
