---
- name: '{{ ansible_name_module }} | cmd:podman.rm | Podman purge runner' 
  command:
    cmd: 'podman rm --force runner'
  no_log: true
  ignore_errors: true
  when: pod_force_rm == true

- name: '{{ ansible_name_module }} | file:absent | Podman purge runner' 
  file:
    path: '{{ dir_tmp }}/{{ name_pod_cloudctl }}-runner.pid'
    state: absent
  when: pod_force_rm == true

- name: '{{ ansible_name_module }} | cmd:podman.run | Podman create {{ name_pod_cloudctl }}' 
  command:
    cmd:
      podman run --rm -dt --name runner
          --pod {{ name_pod_cloudctl }}
          --volume /root/platform/iac:/usr/share/ansible-runner-service/project:z
          --volume {{ dir_secrets }}/cloudctl/certs/ssl/server/cloudctl.crt:/etc/ansible-runner-service/certs/server/ca.crt:z
          --volume /root/platform/runner/usr/share/ansible-runner-service:/usr/share/ansible-runner-service:z
          --volume {{ dir_secrets }}/cloudctl/certs/ssl/server/cloudctl.crt:/etc/ansible-runner-service/certs/server/server.crt:z
          --volume {{ dir_secrets }}/cloudctl/certs/ssl/server/cloudctl.pem:/etc/ansible-runner-service/certs/server/server.key:z
        docker.io/containercraft/ansible-runner-service:latest
  args:
    creates: "{{ dir_tmp }}/{{ name_pod_cloudctl }}-runner.pid"
  register: runner_pid
         #--volume /root/platform/runner/etc/ansible-runner-service:/etc/ansible-runner-service:z
#         --pod-id-file {{ dir_tmp }}/{{ name_pod_cloudctl }}.pid
#         --cidfile {{ dir_tmp }}/{{ name_pod_cloudctl }}-registry.pid
#         --pull missing \
