---
- name: '{{ ansible_name_module }} | cmd:podman.rm | Podman purge konductor' 
  command:
    cmd: 'podman rm --force konductor'
  no_log: true
  ignore_errors: true
  when: pod_force_rm == true

- name: '{{ ansible_name_module }} | file:absent | Podman purge konductor' 
  file:
    path: '{{ dir_tmp }}/{{ name_pod_cloudctl }}-konductor.pid'
    state: absent
  when: pod_force_rm == true

- name: '{{ ansible_name_module }} | cmd:podman.run | Podman create {{ name_pod_cloudctl }}' 
  command:
    cmd:
      podman run -dt --name konductor
          --volume {{ dir_platform }}:{{ dir_platform }}:z
          --pod-id-file {{ dir_tmp }}/{{ name_pod_cloudctl }}.pid
          --cidfile {{ dir_tmp }}/{{ name_pod_cloudctl }}-konductor.pid
        docker.io/containercraft/konductor
  args:
    creates: "{{ dir_tmp }}/{{ name_pod_cloudctl }}-konductor.pid"
  register: konductor_pid
