---
- name: '{{ ansible_name_module }} | cmd:podman_container | Podman purge {{ module }}' 
  containers.podman.podman_container:
    name: "konductor"
    state: "absent"
  when: pod_force_rm == true

- name: '{{ ansible_name_module }} | cmd:podman.run | Podman create {{ name_pod_cloudctl }}' 
  containers.podman.podman_container:
    name: konductor
    image: "{{ upstream_registry }}/cloudctl/konductor"
    state: "started"
    recreate: "true"
    pod: "cloudctl"
    detach: yes
    volume:
      - "{{ dir_platform }}:{{ dir_platform }}:z"
      - "{{ dir_cloudctl }}:{{ dir_iac }}/cloudctl:z"
      - "{{ dir_secrets }}/ssh/id_rsa_cloudctl:/root/.ssh/id_rsa:z"
      - "{{ dir_secrets }}/ssh/id_rsa_cloudctl.pub:/root/.ssh/id_rsa.pub:z"
      - "{{ dir_platform }}/secrets/ssh/authorized_keys:/root/.ssh/authorized_keys:z"
