---
collections:
  - name: amazon.aws
  - name: github3.py
  - name: sparta.collector
  - name: containers.podman
  - name: community.general
  - name: community.libvirt
  - name: community.kubernetes
