---
- name: '{{ ansible_name_module }} | Gather Package Facts on {{ ansible_distribution }}' 
  package_facts:
    manager: auto

# name: '{{ ansible_name_module }} | Check if package requirements met' 
# debug:
#   msg: "{{ ansible_facts.packages['podman'] | length }} requirements met.. skipping task"
# when: "'podman' in ansible_facts.packages"

- name: '{{ ansible_name_module }} | role | Install Dependencies on {{ ansible_distribution }}' 
  include_tasks: packages-{{ ansible_distribution }}.yml
  when: "'podman' not in ansible_facts.packages"
