---
- name: '{{ ansible_name_module }} | cmd:podman.pod.rm | Podman purge {{ name_pod_cloudctl }}' 
  command:
    cmd: 'podman pod rm --force {{ name_pod_cloudctl }}'
# no_log: true
  ignore_errors: true
  when: pod_force_rm == true

- name: '{{ ansible_name_module }} | file:absent | Podman purge {{ name_pod_cloudctl }}' 
  file:
    path: '/tmp/cloudctl/{{ name_pod_cloudctl }}.pid'
    state: absent
  when: pod_force_rm == true

# Need to develop play kube method & dynamic jinja2 template defined pod
# name: '{{ ansible_name_module }} | cmd:podman.play.kube | Podman create CloudCtl' 
# command:
#   cmd: podman play kube /tmp/cloudctl/pod.yml

- name: '{{ ansible_name_module }} | cmd:podman_pod | Podman create {{ module }}' 
  containers.podman.podman_pod:
    name: "{{ name_pod_cloudctl }}"
    hostname: "{{ name_pod_cloudctl }}"
    state: started
    ports:
      - 80:80
      - 443:443
      - 53:5353
      - 5353:5353
      - 2222:2222
      - 6443:6443
      - 8080:8082
      - 8443:8843
      - 5000:5000
      - 5001:5001
      - 22623:22623

# name: '{{ ansible_name_module }} | cmd:podman.pod.create | Podman create {{ name_pod_cloudctl }}' 
# command:
#   cmd:
#    #podman pod create --replace
#     podman pod create
#       --name {{ name_pod_cloudctl }}
#       --hostname {{ name_pod_cloudctl }}
#       --infra-image "k8s.gcr.io/pause:latest"
# args:
#   creates: "/tmp/cloudctl/{{ name_pod_cloudctl }}.pid"
# register: cloudctl_pid
#       --pod-id-file /tmp/cloudctl/{{ name_pod_cloudctl }}.pid
