---
####### Create Unified ArtifactsBundle.tar.gz Tarball with all offline deploy requirements
- name: '{{ ansible_name_module }} | stat | Check for pre-existing ArtifactsBundle.tar.gz.sha256'
  stat:
    path: '/tmp/ArtifactsBundle.tar.gz.sha256'
  register: p1tar_sha_check

###### Download OpenShift Docker Images from Quay.io to File: /root/deploy/mirror/v2
- name: '{{ ansible_name_module }} | block | Download OpenShift images'
  block:

    ####### Purge preexisting bundles
    - name: '{{ ansible_name_module }} | file | Purge pre-existing bundles'
      file:
        path: "{{ local_home }}/ArtifactsBundle.tar.xz"
        state: absent

    ####### Build Unified Bundle
    - name: '{{ ansible_name_module }} | command:tar | build tarball bundle of all artifacts'
      command:
        "tar -c --use-compress-program='pigz -9 ' -v -f /tmp/ArtifactsBundle.tar.xz -C {{ local_home }} deploy"
      args:
        creates: "{{ local_home }}/ArtifactsBundle.tar.xz"
        warn: false

    ####### SHA256sum ArtifactsBundle.tar.xz
    - name: '{{ ansible_name_module }} | stat:sha256 | SHA ArtifactsBundle.tar.xz'
      command:
        "cd /tmp ; sha256sum ArtifactsBundle.tar.xz | tee /tmp/ArtifactsBundle.tar.xz.sha256"

  ####### Block Conditionals
  when: not p1tar_sha_check.stat.exists

####### Build Unified Bundle
- name: '{{ ansible_name_module }} | command:tar.cvf | Build unified bundle with auxilary unpack+launch utilities'
  command:
    "tar -cvf {{ local_home }}/deploy/coffer/coffer-openshift-bundle.{{ version_openshift  }}.tar -C /tmp ArtifactsBundle.tar.xz.sha256 ArtifactsBundle.tar.xz registry.yml registry.sh"
  args:
    creates: "{{ local_home }}/deploy/coffer/coffer-openshift-bundle.{{ version_openshift }}.tar"
    warn: false

####### Bundle ArtifactsBundle.tar.xz with unpack + launch utilities
# name: '{{ ansible_name_module }} | role | archive | Bundle ArtifactsBundle.tar.xz with auxilary files'
# archive:
#   path:
#   - '/tmp/ArtifactsBundle.tar.xz.sha256'
#   - '/tmp/ArtifactsBundle.tar.xz'
#   - '/tmp/registry.yml'
#   - '/tmp/registry.sh'
#   dest: '{{ local_home }}/deploy/{{ cloud_provider }}-{{ target_environment }}-{{ name_cluster_vpc }}-p1bundle.tar'
#   format: tar
