---
- name: '{{ ansible_name_module }} | stage registry startup assets' 
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: '{{ dir_koffer }}/templates/bin/cloudctl.sh.j1', dest: '/tmp/cloudctly.sh' }
    - { src: '{{ dir_koffer }}/templates/pod/cloudctl.yml.j2', dest: '/tmp/cloudctl.yml' }
