---
- name: '{{ ansible_name_module }} | template | Stage CloudCtl Startup Assets' 
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: '{{ dir_koffer }}/templates/bin/start-cloudctl.sh.j2', dest: '/tmp/start-cloudctl.sh' }
    - { src: '{{ dir_koffer }}/templates/pod/cloudctl.yml.j2', dest: '/tmp/cloudctl.yml' }
    - { src: '{{ dir_koffer }}/templates/registry/etc-docker-registry-config.yml.j2', dest: '/root/deploy/mirror/config.yml' }

- name: '{{ ansible_name_module }} | htpasswd | Generate Default Registry Basic Auth'
  htpasswd:
    path: "{{ dir_deploy }}/secrets/registry/auth/htpasswd"
    name: cloudctl
    password: cloudctl
    crypt_scheme: md5_crypt
