#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: ' TPDK | CloudCtl Collector Plugin | bundle.yml' 
  hosts: koffer
  vars_files:
    - 'vars/global.yml'
  vars:
    module: "bundle"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
  tasks:
    
    - name: '{{ ansible_name_module }} | file:absent | Purge pre-existing bundles'
      file:
        path: '{{ item }}'
        state: absent
      loop:
        - "{{ dir_bundle }}/{{ tpdk_bundle_name }}"
        - "{{ dir_cloudctl }}/bundle/{{ bundle_sha }}"
        - "{{ dir_cloudctl }}/bundle/{{ bundle_name }}"
        - "{{ dir_cloudctl }}/.git"
    
    - name: '{{ ansible_name_module }} | command:tar.compress.pigz | Build Platform Artifacts Bundle'
      command:
        "tar -cv --use-compress-program='pigz -9 ' -C {{ dir_local_home }} -f {{ dir_cloudctl }}/bundle/{{ bundle_name }} {{ dir_platform_name }}"
      args:
        creates: '{{ dir_cloudctl }}/bundle/{{ bundle_name }}'
        warn: false
    
    - name: '{{ ansible_name_module }} | stat:sha256 | SHA {{ bundle_name }}'
      command: 'sha256sum {{ bundle_name }}'
      args:
        warn: false
        chdir: '{{ dir_cloudctl }}/bundle'
        creates: '{{ dir_cloudctl }}/bundle/{{ bundle_sha }}'
      register: bundle_sha_sum
    
    - name: '{{ ansible_name_module }} | copy:copy.content | Write Bundle SHA to file'
      copy:
        content: '{{ bundle_sha_sum.stdout }}'
        dest: '{{ dir_cloudctl }}/bundle/{{ bundle_sha }}'
        mode: 0600

    - name: '{{ ansible_name_module }} | command:tar.compress | Build CloudCtl Cradle'
      command:
        cmd:
          tar -cv --use-compress-program='pigz -9' -C {{ dir_local_home }} 
               -f {{ dir_bundle }}/{{ tpdk_bundle_name }} 
             cloudctl
      args:
        chdir: '{{ dir_local_home }}'
        creates: '{{ dir_bundle }}/{{ tpdk_bundle_name }}'
        warn: false

    - name: '{{ ansible_name_module }} | file:mode.0755 | Set Permissions on bundle'
      file:
        path: '{{ dir_bundle }}'
        owner: root
        group: root
        mode: 0755
        state: directory
        recurse: yes
