#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: ' TPDK | CloudCtl Collector Plugin | config.yml' 
  hosts: koffer
  vars_files:
    - 'vars/global.yml'
  vars:
    module: "config"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
  tasks:
    - name: '{{ ansible_name_module }} | template | Stage CloudCtl Startup Assets' 
      template:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
        mode: '{{ item.mode }}'
      with_items:
        - { mode: '0644', src: 'registry/etc-docker-registry-config.yml.j2', dest: '/root/platform/mirror/config.yml' }
