name: coredns
on:
  repository_dispatch:
    types: [coredns]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Login public.ecr.aws
      uses: docker/login-action@v1.9.0
      with:
        logout: false
        registry: public.ecr.aws
        username: ${{ secrets.ROBOT_KEY_ID_AWS_ECR }}
        password: ${{ secrets.ROBOT_SECRET_KEY_AWS_ECR }}
      env:
        AWS_REGION: us-east-1

    - name: Login ghcr.io
      uses: docker/login-action@v1.9.0
      with:
        logout: false
        registry: ghcr.io
        username: ${{ secrets.ROBOT_USER_GHCR }}
        password: ${{ secrets.ROBOT_TOKEN_GHCR }}

    - name: Login Docker.io
      uses: docker/login-action@v1.9.0
      with:
        logout: false
        registry: docker.io
        username: ${{ secrets.ROBOT_USER_DOCKERHUB }}
        password: ${{ secrets.ROBOT_TOKEN_DOCKERHUB }}

    - name: Login Quay.io
      uses: docker/login-action@v1.9.0
      with:
        logout: false
        registry: quay.io
        username: ${{ secrets.ROBOT_USER_QUAY }}
        password: ${{ secrets.ROBOT_TOKEN_QUAY }}

    - name: Git Checkout
      uses: actions/checkout@v2.3.4

    - name: Build Image 
      uses: docker/build-push-action@v2.6.1
      with:
        context: ./containers/${{ github.workflow }}
        file: ./containers/${{ github.workflow }}/Dockerfile
        platforms: linux/amd64
        pull: true
        push: true
       #load: true
        tags: |
          quay.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}
          quay.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}:main-${{ github.sha }}
          docker.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}
          docker.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}:main-${{ github.sha }}
