name: koffer
on:
  schedule:
    - cron: '0 1 * * *'
  push:
    paths-ignore:
    - 'docs/**'
    - '**.md'
    branches: 
      - main
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '**.md'
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

#   - name: Login public.ecr.aws
#     uses: docker/login-action@v1
#     with:
#       logout: true
#       registry: public.ecr.aws
#       username: ${{ secrets.ROBOT_USER_ECR }}
#       password: ${{ secrets.ROBOT_TOKEN_ECR }}
#         public.ecr.aws/b7j0f4t8/${{ github.workflow }}
#         public.ecr.aws/b7j0f4t8/${{ github.workflow }}:${{ env.varveropenshift }}


    - name: Login ghcr.io
      uses: docker/login-action@v1
      with:
        logout: true
        registry: ghcr.io
        username: ${{ secrets.ROBOT_USER_GHCR }}
        password: ${{ secrets.ROBOT_TOKEN_GHCR }}

    - name: Login Docker.io
      uses: docker/login-action@v1
      with:
        logout: true
        registry: docker.io
        username: ${{ secrets.ROBOT_USER_DOCKERHUB }}
        password: ${{ secrets.ROBOT_TOKEN_DOCKERHUB }}

    - name: Login Quay.io
      uses: docker/login-action@v1
      with:
        logout: true
        registry: quay.io
        username: ${{ secrets.ROBOT_USER_QUAY }}
        password: ${{ secrets.ROBOT_TOKEN_QUAY }}

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Rake Variables
      run: |
        set -x ; \
        echo "varrundate=$(date +%y%m%d%I%M%S)" >> ${GITHUB_ENV};\
        echo "varverhelm=$(curl -sL https://api.github.com/repos/helm/helm/releases/latest | jq -r '.tag_name' | sed 's/v//g')" >> ${GITHUB_ENV};\
        echo "varverjq=$(curl -sL https://api.github.com/repos/stedolan/jq/releases/latest | jq -r '.tag_name' | sed 's/jq-//g')" >> ${GITHUB_ENV};\
        echo "varvergrpcurl=$(curl -sL https://api.github.com/repos/fullstorydev/grpcurl/releases/latest | jq -r '.tag_name' | sed 's/v//g')" >> ${GITHUB_ENV};\
        echo "varverterraform=$(curl -sL https://api.github.com/repos/hashicorp/terraform/releases/latest | jq -r '.tag_name' | sed 's/v//g')" >> ${GITHUB_ENV};\
        echo "varveropm=$(curl -sL https://api.github.com/repos/operator-framework/operator-registry/releases/latest | jq -r '.tag_name' | sed 's/v//g')" >> ${GITHUB_ENV};\
        echo "varveropenshift=$(curl --silent https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/release.txt | awk '/  Version/{print $2}')" >> ${GITHUB_ENV};\
        echo;  

    - name: Build Image 
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64
        pull: true
        push: true
        tags: |

          ghcr.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}
          ghcr.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}:${{ env.varveropenshift }}

          quay.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}
          quay.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}:latest
          quay.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}:${{ env.varveropenshift }}
          quay.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}:${{ env.varveropenshift }}-${{ env.varrundate }}-${{ github.sha }}

          docker.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}
          docker.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}:latest
          docker.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}:${{ env.varveropenshift }}
          docker.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}:${{ env.varveropenshift }}-${{ env.varrundate }}-${{ github.sha }}

          quay.io/codesparta/${{ github.workflow }}
          quay.io/codesparta/${{ github.workflow }}:latest
          quay.io/codesparta/${{ github.workflow }}:${{ env.varveropenshift }}
          quay.io/codesparta/${{ github.workflow }}:${{ env.varveropenshift }}-${{ env.varrundate }}-${{ github.sha }}
          docker.io/codesparta/${{ github.workflow }}
          docker.io/codesparta/${{ github.workflow }}:latest
          docker.io/codesparta/${{ github.workflow }}:${{ env.varveropenshift }}
          docker.io/codesparta/${{ github.workflow }}:${{ env.varveropenshift }}-${{ env.varrundate }}-${{ github.sha }}

          quay.io/containercraft/${{ github.workflow }}
          quay.io/containercraft/${{ github.workflow }}:latest
          quay.io/containercraft/${{ github.workflow }}:${{ env.varveropenshift }}
          quay.io/containercraft/${{ github.workflow }}:${{ env.varveropenshift }}-${{ env.varrundate }}-${{ github.sha }}
          docker.io/containercraft/${{ github.workflow }}
          docker.io/containercraft/${{ github.workflow }}:latest
          docker.io/containercraft/${{ github.workflow }}:${{ env.varveropenshift }}
          docker.io/containercraft/${{ github.workflow }}:${{ env.varveropenshift }}-${{ env.varrundate }}-${{ github.sha }}

        build-args: |
          varVerJq=${{ env.varverjq }}
          varVerOpm=${{ env.varveropm }}
          varVerHelm=${{ env.varverhelm }}
          varRunDate=${{ env.varrundate }}
          varVerGrpcurl=${{ env.varvergrpcurl }}
          varVerOpenshift=${{ env.varveropenshift }}
          varVerTerraform=${{ env.varverterraform }}
