name: koffer
on:
  schedule:
    - cron: '0 1 * * *'
  push:
    paths-ignore:
    - 'docs/**'
    - '**.md'
    branches: 
      - main
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '**.md'
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Login Docker.io
      uses: docker/login-action@v1
      with:
        logout: true
        registry: docker.io
        username: ${{ secrets.ROBOT_USER_DOCKERHUB }}
        password: ${{ secrets.ROBOT_TOKEN_DOCKERHUB }}

    - name: Login Quay.io
      uses: docker/login-action@v1
      with:
        logout: true
        registry: quay.io
        username: ${{ secrets.ROBOT_USER_QUAY }}
        password: ${{ secrets.ROBOT_TOKEN_QUAY }}

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Rake Variables
      run: |
        set -x ; \
        echo "varrundate=$(date +%y%m%d%I%M%S)" >> ${GITHUB_ENV};\
        echo "varverhelm=$(curl -s https://api.github.com/repos/helm/helm/releases/latest | awk -F '["v,]' '/tag_name/{print $5}')" >> ${GITHUB_ENV};\
        echo "varverjq=$(curl -s https://api.github.com/repos/stedolan/jq/releases/latest | awk -F '["jq-]' '/tag_name/{print $7}')" >> ${GITHUB_ENV};\
        echo "varvergrpcurl=$(curl -s https://api.github.com/repos/fullstorydev/grpcurl/releases/latest | awk -F '["v,]' '/tag_name/{print $5}')" >> ${GITHUB_ENV};\
        echo "varverterraform=$(curl -s https://api.github.com/repos/hashicorp/terraform/releases/latest | awk -F '["v,]' '/tag_name/{print $5}')" >> ${GITHUB_ENV};\
        echo "varveropenshift=$(curl --silent https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/release.txt | awk '/  Version/{print $2}')" >> ${GITHUB_ENV};\
        echo "varveropm=$(curl -s https://api.github.com/repos/operator-framework/operator-registry/releases/latest | awk -F '["v,]' '/tag_name/{print $5}')" >> ${GITHUB_ENV};\
        echo;  

    - name: Build Image | koffer:latest
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64
        pull: true
        push: true
        tags: |

          quay.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}
          quay.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}:${{ env.varveropenshift }}
          quay.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}:${{ env.varveropenshift }}-${{ env.varrundate }}-${{ github.sha }}

          docker.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}
          docker.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}:${{ env.varveropenshift }}
          docker.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}:${{ env.varveropenshift }}-${{ env.varrundate }}-${{ github.sha }}

        build-args: |
          varVerJq=${{ env.varverjq }}
          varVerOpm=${{ env.varveropm }}
          varVerHelm=${{ env.varverhelm }}
          varRunDate=${{ env.varrundate }}
          varVerGrpcurl=${{ env.varvergrpcurl }}
          varVerOpenshift=${{ env.varveropenshift }}
          varVerTerraform=${{ env.varverterraform }}

    - name: Build Image | koffer:extra
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.extra
        platforms: linux/amd64
        pull: true
        push: true
        tags: |

          quay.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}:extra
          quay.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}:extra-${{ env.varrundate }}-${{ github.sha }}

          docker.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}:extra
          docker.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}:extra-${{ env.varrundate }}-${{ github.sha }}
